# Dropwizard Configuration File

server:
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081

logging:
  level: INFO
  loggers:
    "exam": DEBUG

database:
  driverClass: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/postgres
  user: postgres
  password: postgres
  properties:
    charSet: UTF-8
  maxWaitForConnection: 1s
  validationQuery: "SELECT 1"
  minSize: 8
  maxSize: 32
  checkConnectionWhileIdle: false
  evictionInterval: 10s
  minIdleTime: 1 minute
